{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "prometheus-node-exporter.fullname" . }}
  labels:
    {{- include "prometheus-node-exporter.labels" $ | nindent 4 }}
  namespace: {{ include "prometheus-node-exporter.namespace" . }}
spec:
  ingress:
    {{- if .Values.networkPolicy.ingress }}
      {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
    {{- else }}
    - ports:
      - port: {{ .Values.service.port }}
    {{- end }}
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      {{- include "prometheus-node-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
